WebBooks/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from catalog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path('authors_add', views.authors_add, name='authors_add'),
    path('edit1/<int:id>', views.edit1, name='edit1'),
    re_path('create', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

catalog/urls.py
from django.urls import path, re_path
from .import views


urlpatterns = [
    path('', views.index, name='index')
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Введите жанр книго', verbose_name='Жанр книги')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20, help_text='Введите язык книги', verbose_name='Язык книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text='Введите имя автора', verbose_name='Имя автора')
    last_name = models.CharField(max_length=100, help_text='Введите фамилию автора', verbose_name='Фамилия автора')
    date_of_birth = models.DateField(help_text='Введите дату рождения', verbose_name='Дата рождения', null=True, blank=True)
    date_of_death = models.DateField(help_text='Введите дату смерти', verbose_name='Дата смерти', null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200, help_text='Введите название книги', verbose_name='Название книги')
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text='Выберите жанр книги', verbose_name='Жанр книги', null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text='Выберите язык книги', verbose_name='Язык книги', null=True)
    author = models.ManyToManyField('Author', help_text='Выберите автора книги', verbose_name='Автор книги')
    summary = models.TextField(max_length=1000, help_text='Введите краткое описание книги', verbose_name='Анотация книги')
    isbn = models.CharField(max_length=13, help_text='Должно содержать 13 символов', verbose_name='ISBN книги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Авторы'


class Status(models.Model):
    name = models.CharField(max_length=20, help_text='Введите статус экземпляра книги', verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, help_text='Введите инвентарный номер экземпляра', verbose_name='Инвентарный номер', null=True)
    imprint = models.CharField(max_length=200, help_text='Введите издательство и год выпуска', verbose_name='Издательство')
    status = models.ForeignKey('Status', on_delete=models.CASCADE, help_text='Изменить состояние экземпляра', verbose_name='Статус экземпляра книги', null=True)
    due_back = models.DateField(help_text='Введите конец срока статуса', verbose_name='Дата окончяания статуса')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, help_text='Выберите заказчика книги', verbose_name='Заказчик', null=True, blank=True)

    class Meta:
        ordering = ['due_back']

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label='Имя автора')
    last_name = forms.CharField(label='Фамилия автора')
    date_of_birth = forms.DateField(label='Дата рождения', initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label='Дата смерти', initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
from django.http import *
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AuthorsForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'index.html', context={'num_books': num_books,
                                                  'num_instances': num_instances,
                                                  'num_instances_available': num_instances_available,
                                                  'num_authors': num_authors,
                                                  'num_visits': num_visits})


class BookListView(generic.ListView):
    model = Book
    paginate_by = 4


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='2').order_by('due_back')


def authors_add(request):
    author = Author.objects.all()
    authors_form = AuthorsForm()
    return render(request, 'catalog/authors_add.html',
                  {'form': authors_form, 'author': author})


def create(request):
    if request.method == 'POST':
        author = Author()
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors_add/')


def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect('/authors_add')
    except Author.DoesNotExist:
        return HttpResponseNotFound('<h2>Автор не найден</h2>')


def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == 'POST':
        author.first_name = request.POST.get('first_name')
        author.last_name = request.POST.get('last_name')
        author.date_of_birth = request.POST.get('date_of_birth')
        author.date_of_death = request.POST.get('date_of_death')
        author.save()
        return HttpResponseRedirect('/authors_add/')
    else:
        return render(request, 'catalog/edit1.html', {'author': author})

templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}<title>Мир книг</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Добавление статического CSS-файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block head %}
        <img src="{% static 'images/logotip.jpg' %}" style="width:100px; height:100px;" align="absmiddle">
        <font size=7, color="blue">Сайт "Мир книг"</font>
    {% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Главная страница</a></li>
                    <li><a href="{% url 'books' %}">Все книги</a></li>
                    <li><a href="{% url 'authors' %}">Все авторы</a> </li>
                    <li><a href="{% url 'authors_add' %}">Редактировать авторов</a> </li>
                </ul>
                    {% if user.is_authenticated %}
                        <li>Пользователь: {{ user.get_username }}</li>
                        <li><a href="{% url 'my-borrowed' %}">Мои заказы</a> </li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a> </li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a> </li>
                    {% endif %}
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                                    Предыдущая</a>
                                {% endif %}
                                <span class="page-current">
                                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}
                {% block footer %}
                    {% block copyright %}
                <p>Copyright OOO "piss and shit", 2022. All shits reserved</p>
                    {% endblock %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{%  block content %}
    <h1>Список авторов в БД</h1>
    {% if author_list %}
        {% for author in author_list.all %}
            <p>{{ author.first_name }}  {{ author.last_name }},
               <strong>Родился - </strong>{{ author.date_of_birth }}
               <strong>Умер - </strong>{{ author.date_of_death }}</p>
        {% endfor %}
        {% else %}
            <p>В базе данных нет авторов</p>
    {% endif %}
{% endblock %}

templates/catalog/authors_add.html
{% extends 'base_generic.html' %}
{% block content %}
    <h3>Список авторов в БД</h3>
    <table>
    <thead><th>ID</th><th>----Name----</th><th>Surname</th><th></th></thead>
    {% if author %}
        {% for author in author.all %}
            <tr>
            <td>{{ author.id }}</td>
            <td>{{ author.first_name }}</td>
            <td>{{ author.last_name }}</td>
            <td><a href="/edit1/{{ author.id }}">Изменить</a>
                <a href="/delete/{{ author.id }}">Удалить</a> </td>
            </tr>
        {% endfor %}
    {% else %}
        <p>В базе данных нет авторов</p>
    {% endif %}
    </table>

    <h3>Добавить в БД автора книги</h3>
    <form method="POST" action="/create">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Сохранить">
    </form>
{% endblock %}

templates/catalog/book_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Удаление книги</h1>
    <p>Вы уверены, что хотите удалить книку: {{ book }}?</p>
    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Да, удалить"/>
    </form>
{% endblock %}

templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Название книги: {{ book.title }}</h1>

    <p><strong>Жанр:</strong> {{ book.genre }}</p>
    <p><strong>Анотация:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Язык:</strong> {{ book.language }}</p>
    {% for author in book.author.all %}
        <p><strong>Автор:</strong>
            <a href="">{{ author.first_name }}
                       {{ author.last_name }}</a></p>
    {% endfor %}
    <div style="margin-left: 20px; margin-top: 20px">
        <h4>Количество экземпляров книг в БД</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr><p class="{% if copy.status == 1 %} text-success
                          {% elif copy.status == 2 %} text-danger
                          {% else %} text-warning
                          {% endif %}"> {{ copy.get_status_display }}</p>
            <p><strong>Издательство:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Инвентарный номер:</strong> {{ copy.id }}</p>
            <p><strong>Статус эксемпляра книги в БД:</strong> {{ copy.status }}</p>
        {% endfor %}
    </div>
{% endblock %}
<p><strong>Автор:</strong> <a href="">{{ author.first_name }} {{ author.last_name }}</a> </p>

templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Список книг в БД</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">
                 {{ book.title }}</a>
                 ({{ book.genre }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Вбазе данных нет книг</p>
{% endif %}
{% endblock %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Взятые книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
        ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет книг со статусом В ЗАКАЗЕ.</p>
    {% endif %}
{% endblock %}

templates/catalog/edit1.html
{% extends "base_generic.html" %}
{% block content %}

  <h3>Список авторов в БД</h3>
  <h4>{{author.first_name}} {{author.last_name}}</h4>

    <form method="POST">
        {% csrf_token %}
        <p> <label>Измените имя</label><br>
            <input type="text" name="first_name"
                   value="{{author.first_name}}" />
        </p>
        <p> <label>Измените фамилию</label><br>
            <input type="text" name="last_name"
                   value="{{author.last_name}}" />
        </p>
        <p> <label>Измените дату рождения</label><br>
            <input type="date" name="date_of_birth"
                   value="{{author.date_of_birth}}"/>
        </p>
        <p> <label>Измените дату смерти</label><br>
            <input type="date" name="date_of_death"
                   value="{{author.date_of_death}}" />
        </p>
        <input type="submit" value="Сохранить" >
    </form>

{% endblock %}

templates/index.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Главная страница</h1>

    <p>Добро пожаловать в <em>Мир книг</em>, Это очень простой
    веб-сайт, написанный на Django. Разработан на Python
    в качестве учебного примера с использованием PyCharm.</p>

<h2>Динамический контент</h2>

    <p>База данных сайта Мир книг содержит следующее
    количество записей:</p>
    <ul>
        <li><strong>Количество кеиг:</strong> {{ num_books }}</li>
        <li><strong>Количество экземпляров книг:</strong> {{ num_instances }}</li>
        <li><strong>Количество экземпляров книг в заказе:</strong> {{ num_instances_available }}</li>
        <li><strong>Количество авторов книг:</strong> {{ num_authors }}</li>
    </ul>
    <p>Колличество посещений данной страницы - {{ num_visits }}</p>
{% endblock %}